/**
 * Log4js
 */
var log4js = require('log4js');
log4js.configure({
	appenders: [
		{ type: 'console' },{
		  type: 'file', 
		  filename: 'logs/access.log', 
		  maxLogSize: 1024 * 1024,
		  backups:4,
		  category: 'normal' 
		}
	],
	replaceConsole: true
});
var logger = log4js.getLogger('normal');
//logger.setLevel('INFO');
exports.trace = function(msg) {
	logger.trace(msg);
};
exports.debug = function(msg) {
	logger.debug(msg);
};
exports.info = function(msg) {
	logger.info(msg);
};
exports.warn = function(msg) {
	logger.warn(msg);
};
exports.error = function(msg) {
	logger.error(msg);
};
exports.fatal = function(msg) {
	logger.fatal(msg);
};

/** If u are interested in our code and would like to make it robust, just contact us^^  <snail.liuwei#gmail.com> **/
/** Generated by SNAIL. **/